---
- name: "prem : provision : Generate infrastructure inventory {{r_infra_dir_conf}}/inventory/infra.yml"
  template:
    src: "templates/inventory.j2"
    dest: "{{r_infra_dir_conf}}/inventory/infra.yml"
    mode: 0664
    owner: "{{ r_libre_user }}"
    group: "{{ r_libre_group }}"
- name: "prem : provision : TODO !!!"
  debug:
    msg: "prem : provision : TODO !!!"
