## LIBRE Instructor role tasks
---
- name: "Action {{ do | default('load') | string }} in instructor role is supported"
  assert:
    msg: "Action {{ do | default('load') | string }} in instructor role is not supported"
    that: "do|default('load')|string in ['load','status','install','uninstall']"
- name: "{{ do | default('load') | string }} instructor environement"
  include_tasks: "{{ do | default('load') | string }}.yml"
  when: "do|default('load')|string in ['load','status','install','uninstall']"