---
# Uninstall pre-tasks

# Uninstall tasks
- name: "uninstall : Start training_repo uninstall"
  include_role: 
    name: training_repo
    tasks_from: uninstall
  become: yes
- name: "uninstall : Get previous report data"
  set_fact:
    previous_report: "{{ lookup('file', r_libre_tmp + '/' + r_instructor_tmpfile) | default('') }}"
  delegate_to: localhost
- name: "uninstall : Generate LIBRE report at {{ r_libre_tmp }}/{{ r_instructor_tmpfile }}"
  template:
    src: templates/libre_report-uninstall.j2
    dest: "{{ r_libre_tmp }}/{{ r_instructor_tmpfile }}"
    mode: 0664
  delegate_to: localhost
- name: "uninstall : Log uninstall action"
  include_role:
    name: libre
    tasks_from: lib/log
  vars: 
    log_name: "Instructor workstation is uninstalled"
    log_component: instructor
    log_action: uninstall
