---
- name: "Uninstall instructor environment on {{ target }}"
  hosts: '{{ target }}'
  gather_facts: true
  user: root
  
  roles:
    - { role: instructor, do: load }
    - { role: instructor, do: uninstall, become: yes, libre_uninstall_deep: true }
