---
- name: "Uninstall instructor environment on instructor"
  hosts: 'instructor'
  gather_facts: true
  user: root

  roles:
    - { role: instructor, do: load }
    - { role: instructor, do: uninstall, become: yes }
#    - { role: instructor, do: uninstall, become: yes, libre_uninstall_deep: true }
