---
- name: "Update instructor environment on {{ target }}"
  hosts: '{{ target }}'
  gather_facts: true

  roles:
    - { role: repository, do: load, become: yes }
    - { role: repository, do: update, become: yes }
