---
- name: "Update instructor environment on {{ target }}"
  hosts: '{{ target }}'
  gather_facts: true
  
  roles:
    - { role: training_repo, do: load, become: yes }
    - { role: training_repo, do: update, become: yes }
