## LIBRE Session role default variables


# Instructor directory inside the course directory
r_session_dir_course_playbooks: "{{ training_dir_course_playbooks | default('playbooks/instructor') | string }}"

# Course directory used for delivering training
r_session_dir_course: "{{ training_dir_course | default('/libre/course') | string }}"

# Config file for session
r_session_config_file: "{{ libre_config_file_session | default('session.json') | string }}"
