## LIBRE Chapter role tasks
---
- name: "Action {{ do | default('load') | string }} in chapter role is supported"
  assert:
    msg: "Action {{ do | default('load') | string }} in chapter role is not supported"
    that: "do|default('load')|string in ['load','list','status','start','stop']"
- name: "{{ do | default('load') | string }} chapter environement"
  include_tasks: "{{ do | default('load') | string }}.yml"
  when: "do|default('load')|string in ['load','list','status','start','stop']"