---
- name: "install-precheck : Start instructor pre-installation checks"
  include_role: 
    name: instructor
    tasks_from: "install-precheck.yml"
  when: libre_instructor_install_precheck is undefined or libre_instructor_install_precheck != true
- name: "install-precheck : Mark session install-precheck as done"
  set_fact: libre_session_install_precheck=true