---
- name: "install-precheck : Start repository pre-installation checks"
  include_role:
    name: repository
    tasks_from: "install-precheck.yml"
  when: libre_repository_install_precheck is undefined or libre_repository_install_precheck != true
- name: "install-precheck : Mark session install-precheck as done"
  set_fact: libre_session_install_precheck=true
