---
- name: "load : Get session configuration file details"
  stat:
    path: "{{ r_session_dir_conf }}/{{ conf2.file }}"
  loop: "{{ r_session_conf_list }}"
  loop_control:
    loop_var: conf2
  register: r_session_conf_details
- name: "load : Get session file details from {{ r_session_dir_facts }} facts"
  stat:
    path: "{{ r_session_dir_facts }}/{{ conf.key }}.fact"
  loop: "{{ r_session_conf_list }}"
  loop_control:
    loop_var: conf
  register: r_session_conflinks_details
- name: "load : Load session facts from local facts"
  set_fact: 
    libre_session: "{{ ansible_local.session }}"
  when: 
    - ansible_local is defined
    - ansible_local.session is defined
    - ansible_local.session != "error loading fact - please check content" 
- name: "load : Get {{ r_session_dir_course }} directory details"
  stat:
    path: "{{ r_session_dir_course }}"
  register: r_session_dir_course_details
- name: "load : Get {{ r_session_dir_course }}/manifest.yml file details"
  stat:
    path: "{{ r_session_dir_course }}/manifest.yml"
  register: r_session_manifest_details
- name: "load : Copy {{ r_session_dir_course }}/manifest.yml on local machine"
  fetch:
    src: "{{ r_session_dir_course }}/manifest.yml"
    dest: "/tmp/libre-course-manifest.yml"
    flat: yes
  when: "r_session_manifest_details.stat.exists == true"
- name: "load : Load course content manifest {{ r_session_dir_course }}/manifest.yml"
  include_vars:
    file: "/tmp/libre-course-manifest.yml"
    name: libre_course
  when: "r_session_manifest_details.stat.exists == true"
- name: "load : Get session configuration file details"
  stat:
    path: "{{ r_session_dir_conf }}/{{ conf2.file }}"
  loop: "{{ r_session_conf_list }}"
  loop_control:
    loop_var: conf2
  register: r_session_conf_details

- name: "load : Get {{ r_session_dir_course }}/{{ r_session_dir_course_playbooks }} directory details"
  stat:
    path: "{{ r_session_dir_course }}/{{ r_session_dir_course_playbooks }}"
  register: r_session_dir_course_playbooks_details
- name: "load : Load course"
  include_tasks: "{{ r_session_dir_course }}/{{ r_session_dir_course_playbooks}}/load.yml"
  when: "r_session_dir_course_playbooks_details.stat.exists == true" 
