## LIBRE Session role tasks
---
- name: "Action {{ do | default('load') | string }} in session role is supported"
  assert:
    msg: "Action {{ do | default('load') | string }} in session role is not supported"
    that: "do|default('load')|string in ['load','status','config','install','install-postcheck','start','stop','uninstall']"
- name: "{{ do | default('load') | string }} session environement"
  include_tasks: "{{ do | default('load') | string }}.yml"
  when: "do|default('load')|string in ['load','status','config','install','install-postcheck','start','stop','uninstall']"
