---
- name: "install-postcheck : Training directory detail must exist"
  assert:
    msg: "Training directory detail doesn't exist. Try to re-install LIBRE Toolkit and start again this setup."
    that: r_libre_dir_details is defined
  when: libre_install_postcheck is undefined or libre_install_postcheck != true
- name: "install-postcheck : Training directory {{ r_libre_dir }} must exist"
  assert:
    msg: "Training directory {{ r_libre_dir }} doesn't exist. Try to re-install LIBRE Toolkit and start again this setup."
    that: r_libre_dir_details.stat.exists == true
  when: libre_install_postcheck is undefined or libre_install_postcheck != true
- name: "install-postcheck : Training course directory {{ r_libre_dir_course }} must exist"
  assert:
    msg: "Training course directory {{ r_libre_dir_course }} doesn't exist. Try to re-install LIBRE Toolkit and start again this setup."
    that: r_libre_dir_course_details.stat.exists == true
  when: libre_install_postcheck is undefined or libre_install_postcheck != true
- name: "install-postcheck : Training configuration directory {{ r_libre_dir_conf }} must exist"
  assert:
    msg: "Training configuration directory {{ r_libre_dir_conf }} doesn't exist. Try to re-install LIBRE Toolkit and start again this setup."
    that: r_libre_dir_conf_details.stat.exists == true
  when: libre_install_postcheck is undefined or libre_install_postcheck != true
- name: "install-postcheck : User libre configuration file {{ r_libre_userconfig_dir }}/{{ r_libre_config_file_libre }} exist"
  assert:
    msg: "User libre configuration file {{ r_libre_userconfig_dir }}/{{ r_libre_config_file_libre }} doesn't exist"
    that: r_libre_libre_userconf_details.stat.exists == true
  when: libre_install_postcheck is undefined or libre_install_postcheck != true
- name: "install-postcheck : User libre configuration is loaded"
  assert:
    msg: "Libre configuration {{ r_libre_config_file_libre }} is not loaded"
    that: config_libre is defined
  when: libre_install_postcheck is undefined or libre_install_postcheck != true
- name: "install-postcheck : User session configuration file {{ r_libre_userconfig_dir }}/{{ r_libre_config_file_session }} exist"
  assert:
    msg: "User session configuration file {{ r_libre_userconfig_dir }}/{{ r_libre_config_file_session }} doesn't exist"
    that: r_libre_session_userconf_details.stat.exists == true
  when: libre_install_postcheck is undefined or libre_install_postcheck != true
- name: "install-postcheck : User session configuration is loaded"
  assert:
    msg: "Session configuration {{ r_libre_config_file_session }} is not loaded"
    that: config_session is defined
  when: libre_install_postcheck is undefined or libre_install_postcheck != true
- name: "install-postcheck : User repository configuration file {{ r_libre_userconfig_dir }}/{{ r_libre_config_file_repository }} exist"
  assert:
    msg: "User repository configuration file {{ r_libre_userconfig_dir }}/{{ r_libre_config_file_repository }} doesn't exist"
    that: r_libre_repository_userconf_details.stat.exists == true
  when: libre_install_postcheck is undefined or libre_install_postcheck != true
- name: "install-postcheck : User repository configuration is loaded"
  assert:
    msg: "Session configuration {{ r_libre_config_file_repository }} is not loaded"
    that: config_repository is defined
  when: libre_install_postcheck is undefined or libre_install_postcheck != true
- name: "install-precheck : Mark LIBRE install-postcheck as done"
  set_fact: libre_install_postcheck=true
