---
- name: "install-postcheck : Training directory detail must exist"
  assert:
    msg: "Training directory detail dosen't exist. Try to re-install LIBRE Toolkit and start again this setup."
    that: r_libre_dir_details is defined
- name: "install-postcheck : User libre configuration file {{ r_libre_userconfig_dir }}/{{ r_libre_config_file_libre }} exist"
  assert:
    msg: "User libre configuration file {{ r_libre_userconfig_dir }}/{{ r_libre_config_file_libre }} doesn't exist"
    that: r_libre_libre_userconf_details.stat.exists == true
- name: "install-postcheck : User libre configuration is loaded"
  assert:
    msg: "Libre configuration {{ r_libre_config_file_libre }} is not loaded"
    that: config_libre is defined
- name: "install-postcheck : User session configuration file {{ r_libre_userconfig_dir }}/{{ r_libre_config_file_session }} exist"
  assert:
    msg: "User session configuration file {{ r_libre_userconfig_dir }}/{{ r_libre_config_file_session }} doesn't exist"
    that: r_libre_session_userconf_details.stat.exists == true
- name: "install-postcheck : User session configuration is loaded"
  assert:
    msg: "Session configuration {{ r_libre_config_file_session }} is not loaded"
    that: config_session is defined
- name: "install-postcheck : User repository configuration file {{ r_libre_userconfig_dir }}/{{ r_libre_config_file_repository }} exist"
  assert:
    msg: "User repository configuration file {{ r_libre_userconfig_dir }}/{{ r_libre_config_file_repository }} doesn't exist"
    that: r_libre_repository_userconf_details.stat.exists == true
- name: "install-postcheck : User repository configuration is loaded"
  assert:
    msg: "Session configuration {{ r_libre_config_file_repository }} is not loaded"
    that: config_repository is defined
