---
- name: "install_facts : Create ansible default fact directory {{ r_libre_dir_facts }}"
  file:
    state: directory
    path: "{{ r_libre_dir_facts }}"
    mode: 0665
    owner: root
    group: root
    recurse: yes
- name: "install_facts : Load config fact file detail"
  stat:
    path: "{{ r_libre_dir_facts }}/config.fact"
  register: r_libre_conflinks_details
- name: "install_facts : Create ansible local facts links"
  file:
    state: link
    src: "{{ r_libre_dir_conf }}/{{ r_libre_config_file_libre }}"
    dest: "{{ r_libre_dir_facts }}/config.fact"
    mode: 0664
    owner: root
    group: root
  when: r_libre_conf_details.stat.exists and r_libre_conflinks_details.stat.exists != true
- name: "install_facts : Gathering fresh facts to get LIBRE configuration"
  setup:
  register: r_libre_freshFacts
  when: libre_installed == false
- name: "install_facts : Check if local configuration are in fresh facts"
  fail: msg="Could not find local configuration in ansible_local facts. Check your config directory {{ r_libre_dir_conf }} and {{ r_libre_dir_facts }}"
  when:
    - libre_installed == false
    - (r_libre_freshFacts is undefined or r_libre_freshFacts.ansible_facts is undefined or r_libre_freshFacts.ansible_facts.ansible_local is undefined)
- name: "install_facts : Check if LIBRE configuration is in fresh facts"
  fail: msg="Could not find LIBRE configuration {{ r_libre_config_file_libre }} in ansible_local facts"
  when:
    - libre_installed == false
    - (r_libre_freshFacts.ansible_facts.ansible_local.config is undefined or r_libre_freshFacts.ansible_facts.ansible_local.config == "error loading fact - please check content")
- name: "install_facts : Reload LIBRE configuration facts from fresh facts"
  set_fact:
    libre_config: "{{ r_libre_freshFacts.ansible_facts.ansible_local.config }}" 
    libre_installed: true
  when: libre_installed == false
