---
- name: "load_config : Get configuration file {{ r_libre_userconfig_dir }}/{{ r_libre_config_file_libre }} details"
  stat:
    path: "{{ r_libre_userconfig_dir }}/{{ r_libre_config_file_libre }}"
  register: r_libre_conf_details
  become: no
- name: "load_config : Load LIBRE configuration from {{ r_libre_userconfig_dir }}/{{ r_libre_config_file_libre }}"
  set_fact:
    libre_config: "{{ lookup('file', r_libre_userconfig_dir + '/' + r_libre_config_file_libre) | default('') }}"
  when: r_libre_conf_details.stat.exists == true
  become: no
- name: "load_config : Load default LIBRE configuration"
  set_fact:
    libre_config: "{{ r_libre_config | default('') }}"
  when: r_libre_conf_details.stat.exists != true
