---
- name: "load_software : Get {{ r_libre_dest_bin }}/libre-{{ libre_config.application.type | default('instructor') | string }} file details"
  stat:
    path: "{{ r_libre_dest_bin }}/libre-{{ libre_config.application.type }}"
  register: r_libre_binary_details
