---
- name: "install-precheck : Start LIBRE pre-installation checks"
  include_role: 
    name: libre
    tasks_from: "install-precheck.yml"
  when: libre_install_precheck is undefined or libre_install_precheck != true

- name: "install-precheck : Mark LIBRE install-precheck as done"
  set_fact: libre_training_repository_install_precheck=true
