---
- name: "Update training repository environment on instructor"
  hosts: 'instructor'
  gather_facts: true

  roles:
    - { role: training_repo, do: load }
    - { role: training_repo, do: update, become: yes }
