---
- name: "install_config : Generate {{ r_libre_userconfig_dir }}/{{ r_libre_config_file_libre }}"
  template:
    src: ../templates/libre.j2
    dest: "{{ r_libre_userconfig_dir }}/{{ r_libre_config_file_libre }}"
    mode: 0664
  when: r_libre_conf_details.stat.exists != true
  become: no
- name: "install_config : Reload config file {{ r_libre_userconfig_dir }}/{{ r_libre_config_file_libre }} details"
  stat:
    path: "{{ r_libre_userconfig_dir }}/{{ r_libre_config_file_libre }}"
  register: r_libre_conf_details
  become: no
- name: "install_config : Reload LIBRE configuration from {{ r_libre_userconfig_dir }}/{{ r_libre_config_file_libre }}"
  set_fact:
    libre_config: "{{ lookup('file', r_libre_userconfig_dir + '/' + r_libre_config_file_libre) | default('') }}"
  become: no