## LIBRE Classroom role default variables
---
# Google API to connect to the session description backend
r_infra_prem_gapi_session: "{{ session_gapi_session | default('https://script.google.com/macros/s/XXXXXXX_DOCKEY_XXXXXXXXXXXXXXXXXX/exec') | string }}"


# Set DNS sub-domain to use for deploying DNS classroom names
r_infra_prem_dns_zone: "{{ infra_prem_dns_zone | default('training.example.com') | string }}"
# Set On-premise private key tu use for ssh connection
r_infra_prem_ssh_private_key_file: "{{ infra_prem_ssh_private_key_file | default('~/my-ssh-key.pem') | string }}"
# Set ssh user used to connect to the workstation
r_infra_prem_ssh_user: "{{ infra_prem_ssh_user | default('centos') | string }}"
# Set LIBRE filename used as temporary buffer to send content to the LIBRE command line
r_infra_prem_tmpfile: "{{ libre_tmpfile | default('libre.txt') | string }}"
