---
- name: "setup : Generate infra inventory {{r_infra_prem_dir_conf}}/inventory-infra_prem.yml"
  template:
    src: "../templates/inventory-infra.j2"
    dest: "{{r_infra_prem_dir_conf}}/inventory-infra_prem.yml"
    mode: 0664
    owner: "{{ r_libre_user }}"
    group: "{{ r_libre_group }}"
  become: yes
  when: r_infra_prem_inventoryinfra_details.stat.exists != true
- name: "setup : Succesfull setup for Self-Hosted infrastructure"
  debug:
    msg: 
      - " "
      - "Self-Hosted infrastructure for session {{ libre_session.id }} delivering course {{ libre_session.course }}"
      - "is now setup. You can continue this process by :"
      - " "
      - "1. Review and complete inventory {{r_infra_prem_dir_conf}}/inventory-infra_prem.yml"
      - "2. Start provisionning infrastructure by executing the following command :"
      - "   $ libre-infra prem provision"
      - " "
      - "You can also check in {{ r_libre_dest_ansible }}/inventory for sample inventory to use"
      - "before lauching infrastructure provisionning."
      - " "
      - " Have an happy training ;)"
