## LIBRE Classroom role default variables
---
# Google API to connect to the session description backend
r_infra_aws_gapi_session: "{{ session_gapi_session | default('https://script.google.com/macros/s/XXXXXXX_DOCKEY_XXXXXXXXXXXXXXXXXX/exec') | string }}"

# Default r_infra_aws structure
r_infra_aws_public_dns_zone: "{{ infra_aws_public_dns_zone | default('libre.startx.fr') | string }}"
r_infra_aws_access_key: "{{ infra_aws_access_key | default(false) }}"
r_infra_aws_secret_key: "{{ infra_aws_secret_key | default(false) }}"
r_infra_aws_route53_dns_zone: "{{ infra_aws_route53_dns_zone | default('startx.fr') | string }}"
r_infra_aws_region: "{{ infra_aws_region | default('eu-west-1') | string }}"
r_infra_aws_instance_type: "{{ infra_aws_instance_type | default('t2.micro') | string }}"
r_infra_aws_instance_nb: "{{ infra_aws_instance_nb | default(1) | int }}"
r_infra_aws_image: "{{ infra_aws_image | default('ami-3548444c') | string }}"
r_infra_aws_key_name: "{{ infra_aws_key_name | default('ssh-key') | string }}"
r_infra_aws_ssh_private_key_file: "{{ infra_aws_ssh_private_key_file | default('~/.ssh/id_rsa') | string }}"
r_infra_aws_ssh_user: "{{ infra_aws_ssh_user | default('centos') | string }}"
# Set LIBRE filename used as temporary buffer to send content to the LIBRE command line
r_infra_aws_tmpfile: "{{ libre_tmpfile | default('libre.txt') | string }}"

# Default system user for instructor
r_infra_aws_user_instructor: "{{ infra_user_instructor | default('instructor') | string }}"
# Default system user for students
r_infra_aws_user_student: "{{ infra_user_student | default('student') | string }}"
# Default system user group 
r_infra_aws_usergroup: "{{ infra_usergroup | default('libre') | string }}" 
# Configuration directory used for delivering training
r_infra_aws_dir_conf: "{{ training_dir_conf | default('/libre/conf') | string }}"

