---
- name: "config : Config AWS infrastructure"
  include_tasks: "aws/config.yml"
  when: libre_infra.type == 'aws'
- name: "config : Config On-Premise infrastructure"
  include_tasks: "prem/config.yml"
  when: libre_infra.type == 'prem'
- name: "config : Config Self-Hosted infrastructure"
  include_tasks: "self/config.yml"
  when: libre_infra.type == 'self' or libre_infra is undefined
- name: "config : Reload infra configuration file details"
  stat:
    path: "{{ r_infra_dir_conf }}/{{ r_infra_config_file }}"
  register: r_infra_conf_details
- name: "config : Log config action"
  include_role:
    name: libre
    tasks_from: lib/log
  vars:
    log_name: "Infrastructure is configured"
    log_component: infra
    log_action: config
