---
# Install pre-tasks
- name: "install : Start repository pre-installation checks"
  include_tasks: "install-precheck.yml"
  when: r_repository_install_precheck is undefined or r_repository_install_precheck != true

# Install tasks
- name: "install : Start LIBRE install"
  include_role:
    name: libre
    tasks_from: install
  when: libre_installed == false
- name: "install : Generate {{ r_libre_dir_conf }}/{{ r_repository_config_file }}"
  template:
    src: templates/repository.j2
    dest: "{{ r_libre_dir_conf }}/{{ r_repository_config_file }}"
    mode: 0664
    owner: "{{ r_libre_user }}"
    group: "{{ r_libre_group }}"
  when: r_repository_conf_details.stat.exists != true or libre_repository is undefined
- name: "install : Reload repository configuration file details"
  stat:
    path: "{{ r_libre_dir_conf }}/{{ r_repository_config_file }}"
  register: r_repository_conf_details
- name: "install : Check if repository configuration is in fresh facts"
  fail: msg="Could not find repository configuration {{ r_repository_config_file }} in ansible_local facts"
  when:
    - libre_repository is undefined
    - (r_repository_freshFacts.ansible_facts.ansible_local.repository is undefined or r_repository_freshFacts.ansible_facts.ansible_local.repository == "error loading fact - please check content")
- name: "install : Reload repository configuration facts from fresh facts"
  set_fact:
    libre_repository: "{{ r_repository_freshFacts.ansible_facts.ansible_local.repository }}"
  when: libre_repository is undefined  
- name: "install : Clone course materials from {{ libre_repository.url }} to {{ libre_repository.local }}"
  git:
    clone: yes
    repo: "{{ libre_repository.url }}"
    dest: "{{ libre_repository.local }}"
    version: "{{ libre_repository.branch }}"
  when: r_repository_details.stat.exists != true
- name: "install : Update {{ libre_repository.local }} directory details"
  stat:
    path: "{{ libre_repository.local }}"
  register: r_repository_details
- name: "install : Get previous report data"
  set_fact:
    previous_report: "{{ lookup('file', r_libre_tmp + '/' + r_repository_tmpfile) | default('') }}"
  delegate_to: localhost
  become: no
- name: "install : Generate LIBRE report at {{ r_libre_tmp }}/{{ r_repository_tmpfile }}"
  template:
    src: templates/libre_report-install.j2
    dest: "{{ r_libre_tmp }}/{{ r_repository_tmpfile }}"
    mode: 0664
  delegate_to: localhost
  become: no

# Install post-tasks
- name: "install : Start repository post-installation checks"
  include_tasks: "install-postcheck.yml"
