---
- name: "install-postcheck : Local training repository {{ config_repository.local }} exist"
  assert:
    msg: "Local training repository {{ config_repository.local }} doesn't exist"
    that: r_repository_details.stat.exists == true
