---
- name: "status : Start LIBRE status"
  include_role:
    name: libre
    tasks_from: "status.yml"
- name: "status : Get previous report data"
  set_fact:
    previous_report: "{{lookup('file', r_libre_tmp+ '/' + r_repository_tmpfile) | default('') }}"
  delegate_to: localhost
  become: no
- name: "status : Generate repository report at {{ r_libre_tmp }}/{{ r_repository_tmpfile }}"
  template:
    src: templates/libre_report-status.j2
    dest: "{{ r_libre_tmp }}/{{ r_repository_tmpfile }}"
    mode: 0664
  delegate_to: localhost
  become: no
