---
# Uninstall tasks
- name: "uninstall : Start LIBRE uninstall"
  include_role:
    name: libre
    tasks_from: uninstall
  when: r_libre_uninstall_deep == true
- name: "uninstall : Remove local course repository {{ libre_repository.local }}"
  file:
    state: absent
    path: "{{ libre_repository.local }}"
  when: r_repository_details.stat.exists == true
- name: "uninstall : Remove ansible local facts links"
  file:
    state: absent
    dest: "{{ r_libre_dir_facts }}/repository.fact"
- name: "uninstall : Remove repository configuration file"
  file:
    state: absent
    dest: "{{ r_libre_dir_conf }}/{{ r_repository_config_file }}"
- name: "uninstall : Get previous report data"
  set_fact:
    previous_report: "{{ lookup('file', r_libre_tmp + '/' + r_repository_tmpfile) | default('') }}"
  delegate_to: localhost
  become: no
- name: "uninstall : Generate LIBRE report at {{ r_libre_tmp }}/{{ r_repository_tmpfile }}"
  template:
    src: templates/libre_report-uninstall.j2
    dest: "{{ r_libre_tmp }}/{{ r_repository_tmpfile }}"
    mode: 0664
  delegate_to: localhost
  become: no
