---
# Update tasks
- name: "upgrade : Update course materials from {{ libre_repository.url }}"
  git:
    update: yes
    repo: "{{ libre_repository.url }}"
    dest: "{{ libre_repository.local }}"
    version: "{{ libre_repository.branch }}"
- name: "upgrade : Get previous report data"
  set_fact:
    previous_report: "{{ lookup('file', r_libre_tmp + '/' + r_repository_tmpfile) | default('') }}"
  delegate_to: localhost
  become: no
- name: "upgrade : Generate LIBRE report at {{ r_libre_tmp }}/{{ r_repository_tmpfile }}"
  template:
    src: templates/libre_report-upgrade.j2
    dest: "{{ r_libre_tmp }}/{{ r_repository_tmpfile }}"
    mode: 0664
  delegate_to: localhost
  become: no
